//! SeaORM entities — one [`Entity`](sea_orm::EntityTrait) (+ `Model`) per
//! queried table, generated by hand from `migrations/001..013` (the runtime
//! applies those files; there is no sea-orm-migration crate in the build).
//!
//! Column lists reflect the schema **after** all migrations: `zims.uuid`,
//! `zims.embed_status` / `zims.embed_progress`, `search_history`, and
//! `qid_cache` no longer exist (dropped in 002/004), so no entities are
//! generated for them. `schema_migrations` is tracking-only (raw SQL in
//! [`crate::db::migrate`]) and has no entity.
//!
//! Each module follows the SeaORM 1.1 convention: a `Model` struct with
//! `DeriveEntityModel` (which generates `Entity`, `Column`, `PrimaryKey`,
//! and `ActiveModel`), plus an empty `Relation` enum.
//!
//! `articles_staging` has **no physical primary key** (UNLOGGED COPY staging
//! buffer); it declares `(path, zim_id)` as its ORM primary key because
//! `EntityTrait` requires one. That pair is the table's logical row identity
//! (it mirrors the `articles (zim_id, path)` unique constraint rows merge
//! into) — do not treat it as a physical constraint.
//!
//! Type notes (no first-class sqlx type — raw SQL carries these):
//! - `articles.search_vector` (tsvector) is modeled as `String`; raw SQL
//!   must cast (`search_vector::text`) or use text input (`… ::tsvector`).
//! - `articles.embedding` (pgvector `vector(1536)`) is modeled as
//!   `String` (pgvector text form); raw SQL binds `$n::vector`.

pub mod articles;
pub mod articles_staging;
pub mod collections;
pub mod downloads;
pub mod qid_index;
pub mod settings;
pub mod zims;
